[torch_ops] Report golden_time when it is unset. (#150)
* This change reports the golden time taken by benchmarks that do not
yet have golden time in the error message of the ValueError exception.
E.g.,

```
FAILED generated/AB/256x256xf32_bench/run_module_io.json::AB/256x256xf32_bench - ValueError: golden time has not been set! set it to 0.045276861734397066
```